"""schema inicial v1

Revision ID: 300701077a0d
Revises: 
Create Date: 2026-09-06 17:21:45.756193

Convenção: forward-only. Não escrever ALTER de constraints (DuckDB).
"""
import sqlalchemy as sa
from alembic import op

revision = '300701077a0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE SEQUENCE IF NOT EXISTS seq_arquivo_fonte_id')
    op.execute('CREATE SEQUENCE IF NOT EXISTS seq_sociedade_id')
    op.execute('CREATE SEQUENCE IF NOT EXISTS seq_tema_id')
    op.execute('CREATE SEQUENCE IF NOT EXISTS seq_validacao_id')
    op.execute('CREATE SEQUENCE IF NOT EXISTS seq_edital_id')
    op.execute('CREATE SEQUENCE IF NOT EXISTS seq_proveniencia_id')
    op.execute('CREATE SEQUENCE IF NOT EXISTS seq_edital_cronograma_id')
    op.execute('CREATE SEQUENCE IF NOT EXISTS seq_edital_fase_id')
    op.execute('CREATE SEQUENCE IF NOT EXISTS seq_edital_tema_id')
    op.execute('CREATE SEQUENCE IF NOT EXISTS seq_prova_id')
    op.execute('CREATE SEQUENCE IF NOT EXISTS seq_contexto_id')
    op.execute('CREATE SEQUENCE IF NOT EXISTS seq_questao_id')
    op.execute('CREATE SEQUENCE IF NOT EXISTS seq_alternativa_id')
    op.execute('CREATE SEQUENCE IF NOT EXISTS seq_questao_midia_id')
    op.execute('CREATE SEQUENCE IF NOT EXISTS seq_questao_tema_id')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arquivo_fonte',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('seq_arquivo_fonte_id')"), nullable=False),
    sa.Column('caminho', sa.Text(), nullable=False),
    sa.Column('hash_sha256', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('num_paginas', sa.Integer(), nullable=True),
    sa.Column('ingerido_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo IN ('edital','prova','gabarito_preliminar','gabarito_definitivo','retificacao')", name=op.f('ck_arquivo_fonte_tipo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_arquivo_fonte')),
    sa.UniqueConstraint('hash_sha256', name=op.f('uq_arquivo_fonte_hash_sha256'))
    )
    op.create_table('sociedade',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('seq_sociedade_id')"), nullable=False),
    sa.Column('sigla', sa.Text(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('especialidade', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sociedade')),
    sa.UniqueConstraint('sigla', name=op.f('uq_sociedade_sigla'))
    )
    op.create_table('tema',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('seq_tema_id')"), nullable=False),
    sa.Column('especialidade', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.Text(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tema.id'], name=op.f('fk_tema_parent_id_tema')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tema')),
    sa.UniqueConstraint('especialidade', 'slug', name='uq_tema_especialidade_slug')
    )
    op.create_table('validacao',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('seq_validacao_id')"), nullable=False),
    sa.Column('tabela', sa.Text(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('regra', sa.Text(), nullable=False),
    sa.Column('severidade', sa.Text(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('resolvido', sa.Boolean(), nullable=False),
    sa.Column('resolvido_por', sa.Text(), nullable=True),
    sa.Column('resolvido_em', sa.DateTime(), nullable=True),
    sa.CheckConstraint("severidade IN ('erro','aviso')", name=op.f('ck_validacao_severidade')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validacao'))
    )
    op.create_table('edital',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('seq_edital_id')"), nullable=False),
    sa.Column('sociedade_id', sa.Integer(), nullable=False),
    sa.Column('arquivo_fonte_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('edicao', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('data_publicacao', sa.Date(), nullable=True),
    sa.Column('inscricao_abertura', sa.Date(), nullable=True),
    sa.Column('inscricao_encerramento', sa.Date(), nullable=True),
    sa.Column('taxa_valor', sa.Float(), nullable=True),
    sa.Column('data_prova', sa.Date(), nullable=True),
    sa.Column('local_prova', sa.Text(), nullable=True),
    sa.Column('modalidade', sa.Text(), nullable=True),
    sa.Column('num_questoes_previsto', sa.Integer(), nullable=True),
    sa.Column('nota_minima_aprovacao', sa.Float(), nullable=True),
    sa.Column('pre_requisitos', sa.Text(), nullable=True),
    sa.Column('bibliografia_recomendada', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('vigente', sa.Boolean(), nullable=False),
    sa.CheckConstraint("modalidade IS NULL OR modalidade IN ('presencial','online','hibrida')", name=op.f('ck_edital_modalidade')),
    sa.ForeignKeyConstraint(['arquivo_fonte_id'], ['arquivo_fonte.id'], name=op.f('fk_edital_arquivo_fonte_id_arquivo_fonte')),
    sa.ForeignKeyConstraint(['sociedade_id'], ['sociedade.id'], name=op.f('fk_edital_sociedade_id_sociedade')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edital'))
    )
    op.create_table('proveniencia',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('seq_proveniencia_id')"), nullable=False),
    sa.Column('tabela', sa.Text(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('campo', sa.Text(), nullable=False),
    sa.Column('arquivo_fonte_id', sa.Integer(), nullable=False),
    sa.Column('pagina', sa.Integer(), nullable=True),
    sa.Column('bbox', sa.Text(), nullable=True),
    sa.Column('trecho_fonte', sa.Text(), nullable=True),
    sa.Column('char_inicio', sa.Integer(), nullable=True),
    sa.Column('char_fim', sa.Integer(), nullable=True),
    sa.Column('modelo', sa.Text(), nullable=True),
    sa.Column('versao_prompt', sa.Text(), nullable=True),
    sa.Column('executado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('confianca', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['arquivo_fonte_id'], ['arquivo_fonte.id'], name=op.f('fk_proveniencia_arquivo_fonte_id_arquivo_fonte')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proveniencia'))
    )
    op.create_table('edital_cronograma',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('seq_edital_cronograma_id')"), nullable=False),
    sa.Column('edital_id', sa.Integer(), nullable=False),
    sa.Column('evento', sa.Text(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['edital_id'], ['edital.id'], name=op.f('fk_edital_cronograma_edital_id_edital')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edital_cronograma'))
    )
    op.create_table('edital_fase',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('seq_edital_fase_id')"), nullable=False),
    sa.Column('edital_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['edital_id'], ['edital.id'], name=op.f('fk_edital_fase_edital_id_edital')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edital_fase'))
    )
    op.create_table('edital_tema',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('seq_edital_tema_id')"), nullable=False),
    sa.Column('edital_id', sa.Integer(), nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=False),
    sa.Column('texto_original', sa.Text(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edital_id'], ['edital.id'], name=op.f('fk_edital_tema_edital_id_edital')),
    sa.ForeignKeyConstraint(['tema_id'], ['tema.id'], name=op.f('fk_edital_tema_tema_id_tema')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edital_tema'))
    )
    op.create_table('prova',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('seq_prova_id')"), nullable=False),
    sa.Column('sociedade_id', sa.Integer(), nullable=False),
    sa.Column('edital_id', sa.Integer(), nullable=True),
    sa.Column('arquivo_fonte_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('edicao', sa.Integer(), nullable=False),
    sa.Column('tipo_caderno', sa.Text(), nullable=True),
    sa.Column('num_questoes_declarado', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('ingerida','gabarito_carregado','classificada','completa','caderno_nao_canonico')", name=op.f('ck_prova_status')),
    sa.ForeignKeyConstraint(['arquivo_fonte_id'], ['arquivo_fonte.id'], name=op.f('fk_prova_arquivo_fonte_id_arquivo_fonte')),
    sa.ForeignKeyConstraint(['edital_id'], ['edital.id'], name=op.f('fk_prova_edital_id_edital')),
    sa.ForeignKeyConstraint(['sociedade_id'], ['sociedade.id'], name=op.f('fk_prova_sociedade_id_sociedade')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prova'))
    )
    op.create_table('contexto',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('seq_contexto_id')"), nullable=False),
    sa.Column('prova_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.CheckConstraint("tipo IN ('caso_clinico','texto_base','tabela')", name=op.f('ck_contexto_tipo')),
    sa.ForeignKeyConstraint(['prova_id'], ['prova.id'], name=op.f('fk_contexto_prova_id_prova')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contexto'))
    )
    op.create_table('questao',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('seq_questao_id')"), nullable=False),
    sa.Column('prova_id', sa.Integer(), nullable=False),
    sa.Column('identificador', sa.Text(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('contexto_id', sa.Integer(), nullable=True),
    sa.Column('enunciado', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('gabarito_preliminar', sa.Text(), nullable=True),
    sa.Column('gabarito_oficial', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('justificativa_alteracao', sa.Text(), nullable=True),
    sa.Column('revisada_por_humano', sa.Boolean(), nullable=False),
    sa.CheckConstraint("status IN ('valida','anulada','gabarito_alterado')", name=op.f('ck_questao_status')),
    sa.CheckConstraint("tipo IN ('multipla_escolha','discursiva','verdadeiro_falso')", name=op.f('ck_questao_tipo')),
    sa.ForeignKeyConstraint(['contexto_id'], ['contexto.id'], name=op.f('fk_questao_contexto_id_contexto')),
    sa.ForeignKeyConstraint(['prova_id'], ['prova.id'], name=op.f('fk_questao_prova_id_prova')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questao')),
    sa.UniqueConstraint('identificador', name=op.f('uq_questao_identificador'))
    )
    op.create_table('alternativa',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('seq_alternativa_id')"), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('letra', sa.Text(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('correta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['questao.id'], name=op.f('fk_alternativa_questao_id_questao')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alternativa')),
    sa.UniqueConstraint('questao_id', 'letra', name='uq_alternativa_questao_letra')
    )
    op.create_table('questao_midia',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('seq_questao_midia_id')"), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('caminho_arquivo', sa.Text(), nullable=False),
    sa.Column('legenda', sa.Text(), nullable=True),
    sa.Column('pagina', sa.Integer(), nullable=True),
    sa.Column('bbox', sa.Text(), nullable=True),
    sa.CheckConstraint("tipo IN ('imagem','tabela','grafico')", name=op.f('ck_questao_midia_tipo')),
    sa.ForeignKeyConstraint(['questao_id'], ['questao.id'], name=op.f('fk_questao_midia_questao_id_questao')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questao_midia'))
    )
    op.create_table('questao_tema',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('seq_questao_tema_id')"), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('confianca', sa.Float(), nullable=True),
    sa.Column('classificado_em', sa.DateTime(), nullable=True),
    sa.Column('modelo', sa.Text(), nullable=True),
    sa.CheckConstraint('confianca IS NULL OR (confianca >= 0 AND confianca <= 1)', name=op.f('ck_questao_tema_confianca')),
    sa.ForeignKeyConstraint(['questao_id'], ['questao.id'], name=op.f('fk_questao_tema_questao_id_questao')),
    sa.ForeignKeyConstraint(['tema_id'], ['tema.id'], name=op.f('fk_questao_tema_tema_id_tema')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questao_tema')),
    sa.UniqueConstraint('questao_id', 'tema_id', name='uq_questao_tema_questao_tema')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Projeto usa migrações forward-only; downgrade não suportado.")
